### ISSUE TITLE
AUC + validacion + graficos

### ISSUE THREAD

**Issue by castudil** [Guigna/CKTSOM#1]
- [x] Terminar de implementar la metodologia de valicdacion de one class SOM
- [x] Agregar a readme ejemplos de ejecucion
- [x] Agregar al readme URL pagina del profesor David Tax
http://prlab.tudelft.nl/users/david-tax
- [x] Agregar al readme URL pagina actual de la bilioteca de datasets de one-class classification  
http://homepage.tudelft.nl/n9d04/occ/index.html
- [x] Actualizar graficos que hoy muestra los valores de SIgma vs el Folwlkes-Mallows index por un grafico de SIgma vs AUC.
- [x] funcion en R que realice toda esta valicaion y que devuyelva los 5 AUC respectivos.

**Comment by castudil** [comment]
- [x] falta corregir algunos Bugs en la implematacion de los graficos AUC vs Zscore.
- [x] falta agregar la documentacion de los ejemplos en el Readme.
- [x] Los niveles de los labels deben estar entre 1 y 2, y no entre 0 y 1 como ahora. (linea 224)
- [x] Generalizar el "strata"  para que pueda trabajar con un numero arbitrario de porcentaje train-test
- [x] la palabra es Settings
- [x] cambiar nobre funcion AUC, por  validate5x10cv()
- [x] despues de la visualizacion, agregar codigo que calcue el AUC  maximo  y que entrege el para (theta, AUC) maximo.
- [x]  tomar tablas de webpage, considerar solo las dos primeras columnas. agregar fila the CKTSOM, con el maximo AUC encontrado. ademas debemos registrar internamente cuale es el theta que genera este resultado.
- [x]  Genrar graficos respectivo par el maximo numero de dataset esta semana.

**Comment by castudil** [comment]
- [x] ejecutar los otros datasets, y verificar si exite otro dataset en que nuestro algorimo muestre ventajas. tratar de encontrtar patrones en comun entre estos dataset. por jemeplo, muchas dimensiones, muchas instancias, origen de los datos (me parece quie los datos dieabtes arrojaron buenos buenos resultados. quizas datos de medician andan bien, o de analisis quimico de sangre.)

- [ ] realizar PCA patra datasets en que el cuento anada bien. la razon es tratar de encontrar patrones. por ejemplo, cuantos componenetes principales se requieren para representar el 85 porciento de los datos? esto nos permite saber que tan comprimida esta la informacion.

- [ ] aplicar metodologia de aprendizaje a lois datos PCA-diabetes, para ver si todavia andamos bien.



correcciones pequeñas:

- [x] falta corregir algunos Bugs en la implematacion de los graficos AUC vs Zscore.
- [x] falta agregar la documentacion de los ejemplos en el Readme.
- [x] Los niveles de los labels deben estar entre 1 y 2, y no entre 0 y 1 como ahora. (linea 224)
- [x] Generalizar el "strata"  para que pueda trabajar con un numero arbitrario de porcentaje train-test
- [x] la palabra es Settings
- [x] cambiar nobre funcion AUC, por  validate5x10cv()
- [x] despues de la visualizacion, agregar codigo que calcue el AUC  maximo  y que entrege el para (theta, AUC) maximo.

**Comment by castudil** [comment]
hola, veo que estan casi todos los temos marcados como resueltos.
Me puedes hacer una acutalizacion de cuales son tus tareas actuales? codigo, escritura. etc.

**Comment by Litier** [comment]
Realice  las pruebas de AUC con un árbol grande, de 5 niveles y 5 hijos por nodo pero tengo un problema ya que detecta todo como outlaier sin importar el theta. Por esto estoy haciendo las pruebas con distintas combinaciones pero sin un árbol grande por los problemas mencionados
En el escrito avance y empecé a generar las imágenes tanto para el informe como para la ppt

**Comment by castudil** [comment]
conversamos en algún momento acerca de RMSE? Root Mean Squared Error. me da la impresion que para arboles mas grandes estamos teniendo problemas de convergencia. al entrenar mas nodos se necesitan mas iteraciones porque o si no el arbol no se alcance a ordenar adecuadamente. para verificar esto debemos realizar un grafico de convergencia. en este enlace puedes encontrar un ejemplo de grafico:

https://www.r-bloggers.com/self-organising-maps-for-customer-segmentation-using-r/

https://i1.wp.com/shanelynn.ie/wp-content/uploads/2014/01/SOM_training.png?zoom=2&resize=400%2C334

en ese caso se esta grafica la distancia promedio a los nodos (seria equivalente a MSE, o sea sin tomar la raiz cuadrada)

- [x] Implementa una función que calcule el RMSE  (distancia promedio de las instancias a sus BMU al cuadrado y luego tomas la raiz del resultado final) o MSE.
- [ ] crea una función que grafique el RMSE vs número de iteraciones. no tienes para que calcular cada punto del gráfico, se puede hacer cada 100 o 1000 iteraciones. este gráfico nos va a dar mas indicio si es que hay convergencia en el entrenamiento.
